#ifndef SHIORI_COLOR_H
#define SHIORI_COLOR_H

#include <stdbool.h>

enum color_style {
    COLOR_STYLE_RESET,
    COLOR_STYLE_SUCCESS,
    COLOR_STYLE_ERROR,
    COLOR_STYLE_WARNING,
    COLOR_STYLE_INFO,
    COLOR_STYLE_BOLD,
    COLOR_STYLE_TOPIC,
    COLOR_STYLE_TODOS,
    COLOR_STYLE_NOTES,
    COLOR_STYLE_DUE_DATE,
    COLOR_STYLE_HEADING,
    COLOR_STYLE_NOTE_ID,
    COLOR_STYLE_METADATA,
    COLOR_STYLE_OPEN,
    COLOR_STYLE_COMPLETION_REMAINDER,
    COLOR_STYLE_DIVIDER
};

void color_set_enabled(bool enabled);
bool color_is_enabled(void);
const char *color_style_sequence(enum color_style style);

#define ANSI_BOLD "\x1b[1m"
#define ANSI_RESET "\x1b[0m"
#define ANSI_FG_RGB(r, g, b) "\x1b[38;2;" #r ";" #g ";" #b "m"

// Semantic colors
#define COLOR_SUCCESS ANSI_FG_RGB(100, 210, 140)
#define COLOR_ERROR ANSI_FG_RGB(255, 105, 120)
#define COLOR_WARNING ANSI_FG_RGB(255, 190, 80)
#define COLOR_INFO ANSI_FG_RGB(110, 190, 255)

#define COLOR_TOPIC ANSI_FG_RGB(180, 140, 255)
#define COLOR_TAG ANSI_FG_RGB(180, 140, 255)
#define COLOR_TODOS ANSI_FG_RGB(255, 105, 120)
#define COLOR_NOTES ANSI_FG_RGB(110, 190, 255)
#define COLOR_DUE_DATE ANSI_FG_RGB(255, 190, 80)
#define COLOR_HEADING ANSI_FG_RGB(255, 180, 80)
#define COLOR_NOTE_ID ANSI_FG_RGB(105, 135, 160)
#define COLOR_METADATA ANSI_FG_RGB(120, 130, 145)

#define COLOR_OVERDUE COLOR_ERROR
#define COLOR_DUE_TODAY COLOR_WARNING
#define COLOR_IN_PROGRESS COLOR_WARNING
#define COLOR_OPEN ANSI_FG_RGB(110, 190, 255)

// Interactive terminal / completion

#define COLOR_COMPLETION_MATCH COLOR_SUCCESS
#define COLOR_COMPLETION_REMAINDER ANSI_FG_RGB(120, 130, 145)

#define COLOR_DIVIDER ANSI_FG_RGB(90, 105, 120)
#endif
